/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp profilemanager.xml -i profilemanager.h -a profilemanager_adaptor
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "profilemanager_adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class ProfileManagerAdaptor
 */

ProfileManagerAdaptor::ProfileManagerAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

ProfileManagerAdaptor::~ProfileManagerAdaptor()
{
    // destructor
}

int ProfileManagerAdaptor::activeUserId() const
{
    // get the value of property activeUserId
    return qvariant_cast< int >(parent()->property("activeUserId"));
}

void ProfileManagerAdaptor::setActiveUser(int id)
{
    // handle method call com.fpt.fresher.ProfileManager.setActiveUser
    QMetaObject::invokeMethod(parent(), "setActiveUser", Q_ARG(int, id));
}

